services:
  # The Edge AI service
  # run: `docker-compose build` to update the service
  # run: `docker-compose up -d` to launch the service
  processor:
    image: stakach/edgeai
    # build: .
    restart: unless-stopped

    # network, host mode as we need multicast support
    container_name: processor
    hostname: processor
    network_mode: "host"

    volumes:
      - ./config/:/config/
      - /mnt/ramdisk:/mnt/ramdisk
      - ./model_storage/:/model_storage/

      # we need to map in all the USB devices
      # as edge TPU device name changes when initialized
      - /dev/bus/usb:/dev/bus/usb
  
    devices:
      - "/dev/gpiochip0"
    
    ports:
      - "3000:3000"
    environment:
      SG_ENV: "production"

  interface:
    image: stakach/edgeai
    # build: .
    restart: unless-stopped

    # network
    container_name: interface
    hostname: interface
    network_mode: "host"

    volumes:
      - ./clips/:/clips/
      - ./config/:/config/
      - /mnt/ramdisk:/mnt/ramdisk

  frontend:
    image: nginx
    container_name: frontend
    hostname: frontend
    depends_on:
      - interface
    volumes:
      - ./www/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
